# Generated by Django 3.0 on 2022-06-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwrite', '0002_blog_admin_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=65535),
        ),
    ]
