# Generated by Django 3.0 on 2022-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwrite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
